### ISSUE TITLE
DB indexleri

### ISSUE THREAD

**Issue by yamac-kurtulus** [acikkaynak/deprem-yardim-backend#110]
Çok kullanılan modellere index lazım. Örneğin lat/lng datası, (varsa) search alanları

**Comment by yemregundogmus** [comment]
lat long ve 4'lü sorgulardaki veriler indexli, uyarı için teşekkürler.

**Comment by yamac-kurtulus** [comment]
Ha ok, görmedim migration dışından yaptıysanız.
