### ISSUE TITLE
API Dokümanı

### ISSUE THREAD

**Issue by abdyek** [acikkaynak/deprem-yardim-backend#117]
API dokümanı var mı? Yoksa generate edilebiliyor mu?

Bu konu hakkında bilgilendirirseniz sevinirim

**Comment by ytkimirti** [comment]
#66 PR'ı ile swagger entegre olursa ordan görebilirsiniz. Şimdilik `openai/swagger.yaml` dosyasından bakabilirsiniz

**Comment by abdyek** [comment]
Teşekkürler
