### ISSUE TITLE
Kahramanmaraş Merkez adresi girilirken seçilecek ilçe.

### ISSUE THREAD

**Issue by ossarac** [acikkaynak/deprem-yardim-backend#50]
Selamlar. Söyle bir feedback geldi siteyi paylaştıklarımdan. Sayfadan 'Kahramanmaraş merkez' diye bildirilen yardım çağrılarını girmek istediklerinde ilçe listesinde 'Merkez' diye bir seçenek yok ve hangi ilçeyi seçmeleri gerektiğini bilemiyorlar. Sanırım burası Kahramanmaraş için '12 Şubat' (Bunun doğruluğunu teyid etmek lazım). Eğer doğruysa bu seçeneğin yanına parantez içinde (Merkez) yazılabilir mi kolaylık olması için.

Bu issue ilk front-end'de açıldi ancak sanırım doğru yer burası.
Issue'da aşağıdaki gibi bir yorum da geldi [arzucaner](https://github.com/arzucaner)'den:

"Bu tespite katiliyorum. Ozellikle ilgili sehirde yasamayanlar icin bu ayrimi yapmak zor olabilir.

Bu ornege ilaveten;

Gaziantep icin (Sahinbey ve Sehitkamil)
Hatay (Antakya)
Mersin (Akdeniz, Yenisehir, Toroslar, Mezitli)
Adana (Cukurova, Seyhan, Yuregir)
Merkez adi altinda toplanabilir."

**Comment by yemregundogmus** [comment]
Bu konu depremyardim.com ile ilgili sanırım, bu repoda afetharitasi.com'un backend'i bulunuyor.
