### ISSUE TITLE
Add date time to the drawer data

### ISSUE THREAD

**Issue by mertcanaltin** [acikkaynak/deprem-yardim-backend#60]
merhaba front end tarafında tarih ve saat datasına ihtiyacımız var bu konuda yardımcı olabilirseniz çok seviniriz ellerinize sağlık

[front end issue](https://github.com/acikkaynak/deprem-yardim-frontend/issues/186)

**Comment by wioniqle-q** [comment]
> 

@mertcanaltin

**Comment by wioniqle-q** [comment]
Tamam içinden almaya çalışacağım aldığım gibi size dönüş yaparim
