### ISSUE TITLE
Marking error

### ISSUE THREAD

**Issue by hemregur** [acikkaynak/deprem-yardim-backend#61]
Since the name Istanbul is mentioned in the sentence, it marks the address with the same street and apartment name in Istanbul.

**Comment by akarakus27** [comment]
[Mem8](https://github.com/Mem8) commented [1 hour ago](https://github.com/acikkaynak/deprem-yardim-backend/issues/62#issue-1574476223)
Twitterdan alınan kaynak adresin içerisinde olan adresin mahalle/site/cadde isimleri büyükşehirlerde benzerlik gösterdiği durumlarda sistemin önceliği büyükşehirlere verdiğinden dolayı harita üzerinde işaretlemeleri İstanbul/Ankara/İzmir gibi şehirlere konumlandırıyor.

Konu ile ilgili olarak işaretlemelerin yapılacağı durumda sıkıntı yaşanan 10 il ve çevre iller dışındaki iller için ignore edilmeli ve o adresin bu 10 il içerisindeki en yakın sonucun bulunduğu adres işaretlenmeli

**Comment by MahmutVG** [comment]
Bence veritabanına eklenmesinde sakınca yok, ancak front end'e yansıtılması konusunda geojson bazlı ya da postgis geometry ile filtrelenmesi gerekiyor.
