### ISSUE TITLE
Haritada konumların yanlış işaretlenmesi

### ISSUE THREAD

**Issue by Mem8** [acikkaynak/deprem-yardim-backend#62]
Twitterdan alınan kaynak adresin içerisinde olan adresin mahalle/site/cadde isimleri büyükşehirlerde benzerlik gösterdiği durumlarda sistemin önceliği büyükşehirlere verdiğinden dolayı harita üzerinde işaretlemeleri İstanbul/Ankara/İzmir gibi şehirlere konumlandırıyor.

Konu ile ilgili olarak işaretlemelerin yapılacağı durumda sıkıntı yaşanan 10 il ve çevre iller dışındaki iller için ignore edilmeli ve o adresin bu 10 il içerisindeki en yakın sonucun bulunduğu adres işaretlenmeli

**Comment by alperencantez** [comment]
Duplicate #61
