### ISSUE TITLE
collect_tweets task not fully synchronizing with twitter

### ISSUE THREAD

**Issue by WazeHell** [acikkaynak/deprem-yardim-backend#69]
`collect_tweets` configured to run every 300 seconds inside the celery,
meanwhile, the `since_time` variable inside the task is set to 2 minutes only. 

the `since_time` should match the following rule in order to ensure that the platform is not missing any tweets 
since_time > task_interval + last task execution time + 1 minute buffer

**Comment by budancamanak** [comment]
To clarify issue, lines mentioned above are as follows:
https://github.com/acikkaynak/deprem-yardim-backend/blob/bec8e6c68aa892364846b9d132bda437ad113e10/trquake/celery.py#L21
https://github.com/acikkaynak/deprem-yardim-backend/blob/bec8e6c68aa892364846b9d132bda437ad113e10/applications/tweets/tasks.py#L18 

if the issue above exist on production, that means that the system is probably missing some tweets which could be cruical. I believe we could use formula mentioned above to fix.

**Comment by budancamanak** [comment]
updated in [PR](https://github.com/acikkaynak/deprem-yardim-backend/pull/74)
