### ISSUE TITLE
Area filtresi greater_than less_than logic yanlis yazilmis olabilir

### ISSUE THREAD

**Issue by Kayra1** [acikkaynak/deprem-yardim-backend#81]
NE || SE olursa sadece o araliktaki sonucalari paginagate olmadan gonder.

Not: tweets.views line 49

@fdemir: gökata#6419
@usirin: umut#3072

**Comment by fdemir** [comment]
update?

**Comment by mertkaya1033** [comment]
- north-east sag ust kose, south west sol alt kose. 
- Rect icinde olmasi icin sw_lat <= cur_lat <= ne_lat, sw_lng <= cur_lng <= ne_lng olmasi lazim
Degisim boyle olmasi lazim bence:

![image](https://user-images.githubusercontent.com/47050442/217367213-6fb4ffe3-1807-4eec-989e-09624f6b5cb2.png)

Ama local environmentda daha test edemedim (kutuphane internetinden ilk docker setupini yapiyorum)

**Comment by Kayra1** [comment]
Bu olay cozuldu PR aciliyo @fdemir

**Comment by Kayra1** [comment]
Main cok hizli bi sekilde degistigi ve su an deployment icin kimseye ulasamadigimiz icin askiya almak zorunda kaldik.

**Comment by Kayra1** [comment]
Olay cozuldu yakin zamanda deploy edilicek @fdemir
