### ISSUE TITLE
Gereginden fazla data yollaniyor

### ISSUE THREAD

**Issue by Kayra1** [acikkaynak/deprem-yardim-backend#82]
BFF clienta kullanilmayan verileri gonderiyor. [{id, l: [lat, lon]}] gondermen yeterli. user pointe tikladigi zaman ek olarak detail bilgiler tekrar fetch edilecek.

Yeni bir serializer/view gerek.

Frontend takip:

@fdemir: gökata#6419
@usirin: umut#3072

**Comment by ytkimirti** [comment]
Kesinlikle, her seferinde sayfaya girişte 3.8MB bütün json verisi aktarılıyor, kısa vadeli çözüm olarak uzaktan bakarken sadece konum verisi gönderilmesi olabilir

**Comment by fdemir** [comment]
update?

**Comment by ytkimirti** [comment]
Öncelikle frontendin eksik veri ile işleyebilmesi lazım, kim ilgileniyor tam olarak bilmiyorum

**Comment by Kayra1** [comment]
Main cok hizli bi sekilde degistigi ve su an deployment icin kimseye ulasamadigimiz icin askiya almak zorunda kaldik.

**Comment by yamac-kurtulus** [comment]
Bu tamam ama PR linklenmedi. Burada: #101

**Comment by Kayra1** [comment]
linklemek icin PR'dan issue'yu mention etmeniz lazim. `Closes #82` yazin yorumun basina
